name: ":bookmark_tabs: Sugestão/Feedback"
description: "Deixe seu comentário."
title: "Ticket Title"
labels: ["UI"]
assignees:
  - shascher
body:
  - type: textarea
    attributes:
      label: "Comentário"
      description: "Deixe sua sugestão/feedback sobre o projeto"
      placeholder: "Texto."
    validations:
      required: true
  - type: checkboxes
    id: rating
    attributes:
      label: "Avaliação"
      description: Qual a sua avaliação sobre o projeto?
      options:
        - label: bom 
  