version: '3'
services: 

    db:
        build: .
        container_name: pg_container
        environment: 
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=dados_financeiros
        ports:
            - "5432:5432"  
        volumes: 
            - ./data:/var/lib/postgresql/data/
