name: Linter

on: 
  pull_request:
    branches:
    - main
  push:

jobs:
  run_black:
    runs-on: ubuntu-latest
    steps:

      - name: Check conteudo do repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Instala python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instala os pacotes do requirements_dev.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Executa 'Black'
        run: |
          python -m black .     

  run_isort:
    runs-on: ubuntu-latest
    steps:

      - name: Check conteudo do repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Instala python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instala os pacotes do requirements_dev.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Executa 'Isort' 
        run: |
          isort .                 

  run_flake8:
    runs-on: ubuntu-latest
    steps:

      - name: Check conteudo do repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Instala python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instala os pacotes do requirements_dev.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Executa 'Flak8' 
        run: |
          flake8 .  